# Generated by Django 4.2.16 on 2025-02-02 13:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://via.placeholder.com/50', max_length=255, verbose_name='image'),
        ),
    ]
